Added persistent data volume

diff --git a/terraform/cloud_init.yaml b/terraform/cloud_init.yaml
--- a/terraform/cloud_init.yaml
+++ b/terraform/cloud_init.yaml
@@ -8,6 +8,21 @@ write_files:
   permissions: '0600'
   content: |
     /opt/infrastructure
+- path: /opt/disk_setup.sh
+  permissions: '0755'
+  content: |
+    #!/bin/bash
+    [ ! -e /dev/sdb ] && ( echo "Cannot find mount. Aborting." ; exit 1 )
+    # unmount if mounted. Ubuntu will try to automount everything.
+    umount /dev/sdb 2>&1 >/dev/null
+    # Format as EXT4 if not already so.
+    if [[ "$(blkid /dev/sdb)" != *'TYPE="ext4"'* ]] ; then
+      mkfs.ext4 -F /dev/sdb
+    fi
+    # Name volume
+    if [[ "$(e2label /dev/sdb )" != 'data' ]] ; then
+      e2label /dev/sdb data
+    fi
 users:
   - default
   # temporary user. Used to have access to the machine during the transitive period
@@ -20,6 +35,7 @@ users:
       - gh:jamesepatrick
     lock_passwd: false
 runcmd:
+  - /opt/disk_setup.sh
   - >
     git clone https://github.com/jamesepatrick/infrastructure /opt/infrastructure
     ; cd /opt/infrastructure
